### ISSUE TITLE
Comma character in title field breaks output when quotes=true

### ISSUE THREAD

**Issue by cambraca** [seboettg/citeproc-php#106]
- [x] I read the README and followed the instructions.
- [x] I am sure that the used CSL metadata follows the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).
- [x] I use a valid CSL stylesheet

## Bug report:

Rendered bibliography doesn't contain the full title when there's a comma in between.

The `QuotesTrait::addSurroundingQuotes()` method seems to be the culprit.

### Expected:

    <div class="csl-bib-body">
      <div class="csl-entry">“Article Title, With a Comma”. <i>My Publisher</i>.</div>
    </div>

### Actual:

    <div class="csl-bib-body">
      <div class="csl-entry">“ With a Comma”. <i>My Publisher</i>.</div>
    </div>

### Used CSL stylesheet: ####

modern-language-association.csl

### Used CSL metadata ####

Please replace these lines with your used metadata, for instance:

    [
        {
            "id": "ITEM-1",
            "type": "webpage",
            "container-title": "My publisher",
            "title": "Article title, with a comma."
        }
    ]

**Comment by mgip** [comment]
is anyone make work with the API of mendeley?
