### ISSUE TITLE
PHP 8.0 compatibility?

### ISSUE THREAD

**Issue by schnumsel** [seboettg/citeproc-php#111]
# Please follow the general troubleshooting steps first:

- [x] I read the README and followed the instructions.
- [x] I am sure that the used CSL metadata follows the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).
- [x] I use a valid CSL stylesheet

### Bug reports:
Do you plan to support PHP 8 in the near future? I get an error in 
```
src/Seboettg/CiteProc/Styles/AffixesTrait.php
```
in line 74 saying: Array and string offset access syntax with curly braces is no longer supported.

Would be great to fix it so I could upgrade to PHP 8

Best regards and thanks in advance,

Willi

**Comment by seboettg** [comment]
I'm pretty busy currently. I hope I can do it in the early next year.

**Comment by seboettg** [comment]
Hi @schnumsel!
I think citeproc-php is now working with PHP 8.0.
To double check, please checkout the branch `feature/issue-111-php80-compatibility` and test it by running citeproc-php with php 8.0!
Thanks in advance.
