### ISSUE TITLE
Reporting a compatibly issue in DatePart.php files - line 227

### ISSUE THREAD

**Issue by saalam** [seboettg/citeproc-php#142]
Hey @seboettg 

I need you advice to avoid this warning. I'm using OJS and everything is fine when PHP version is 7.4 but it went wrong when I upgraded the PHP version to 8.0. I looked through your repository and find out that the DatePart.php doesn't  support PHP 8.0. Below is the error I'm getting. 

Attempt to read property "single" on null in /********/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Date/DatePart.php on line 227 

line 227:
` $text = CiteProc::getContext()->getLocale()->filter('terms', $month, $form)->single;
`

Your help is highly appreciated. 
Regards,
-Salam

**Comment by seboettg** [comment]
Hi @saalam,
In order to reproduce the issue I need the bibliogrpahic metadata and the used stylesheet.
Thanks in advance,
Sebastian

**Comment by saalam** [comment]
We have more  than 17 journal installed in our system and all of them are using OJS stylesheet. Tbh I don't know how to provide you with the bibliogrpahic metadata and the used stylesheet. But I can show you a sample of the published articles 
[https://journal.uokufa.edu.iq/index.php/kje/article/view/1816](https://journal.uokufa.edu.iq/index.php/kje/article/view/1816)

Style Sheet main site:

`.pkp_page_index .journals img 
{
max-width: 100%;
filter: grayscale(90%);
transition: 0.1s;
cursor: pointer;
}



.pkp_navigation_user_wrapper
{
width: 100%;
}

.pkp_structure_main, .pkp_footer_content
{
font-family: 'Montserrat';
}
.pkp_structure_main p:last-child, .pkp_structure_main p
{
text-align :justify;
}


.pkp_block 
{
font-family: 'Montserrat';
font-size: 13.33px;
line-height: 20px;
clear: both;
border-bottom: 1.5px solid #ddd;
}

.obj_article_summary  
{
padding-bottom: 10px ;
border-bottom: solid 1px #F7BC4A ;
border-bottom-width: 1px ;
}

.hoverTable_Salam
{
width: 100%;
border-collapse: collapse;
}
.hoverTable_Salam tr 
{

border-bottom: 1px solid #ffffff;
padding-top: 1px;
}
.hoverTable_Salam td a 
{
width: 100%;
display: block;
}
.hoverTable_Salam a 
{
color: #ffffff;
}
.hoverTable_Salam td
{
height: 30px;
padding-left: 4px;
vertical-align: middle;
text-align: left;
}

.hoverTable_Salam1 tr
{
background:#006634;
}
.hoverTable_Salam1 td:hover
{
background: #F7BC4A;
}`

Style Sheet  for the a journal
`.block_make_submission a 
{
background: #ed4e32;
}
.cmp_manuscript_button,.obj_galley_link
{
background: #3F688A;
}
.hoverTable_Salam tr
{
background: #053053;
}
td:hover
{
background: #F7BC4A;
}`

I have noticed a new warning regarding the same plugin 
`[02-Nov-2022 18:05:08 ] PHP Warning:  Undefined property: stdClass::$given in /home2/public_html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Name/Name.php on line 579
[02-Nov-2022 18:05:08] PHP Warning:  Undefined property: stdClass::$given in /home2/public_html/plugins/generic/citationStyleLanguage/lib/vendor/seboettg/citeproc-php/src/Rendering/Name/Name.php on line 579`

**Comment by seboettg** [comment]
I'm not similar with OJS. I need a Citation Style and the json formatted metadata.

**Comment by saalam** [comment]
I attached to you a sample. Hope that can helps 
Thanks a lot

`<html>
<body>


<ul class="citation_formats_styles">
--
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acm-sig-proceedings?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acm-sig-proceedings?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | ACM
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acs-nano?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acs-nano?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | ACS
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/apa?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/apa?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | APA
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/associacao-brasileira-de-normas-tecnicas?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/associacao-brasileira-de-normas-tecnicas?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | ABNT
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/chicago-author-date?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/chicago-author-date?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | Chicago
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/harvard-cite-them-right?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/harvard-cite-them-right?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | Harvard
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/ieee?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/ieee?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | IEEE
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/modern-language-association?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/modern-language-association?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | MLA
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/turabian-fullnote-bibliography?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/turabian-fullnote-bibliography?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | Turabian
  | </a>
  | </li>
  | <li>
  | <a
  | aria-controls="citationOutput"
  | href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/vancouver?submissionId=9769&amp;publicationId=9753"
  | data-load-citation
  | data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/vancouver?submissionId=9769&amp;publicationId=9753&amp;return=json"
  | >
  | Vancouver
  | </a>
  | </li>
  | </ul>
  | <div class="label">
  | Download Citation
  | </div>
  | <ul class="citation_formats_styles">


</body>
</html><ul class="citation_formats_styles">
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acm-sig-proceedings?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acm-sig-proceedings?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acm-sig-proceedings?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													ACM
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acs-nano?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acs-nano?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/acs-nano?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													ACS
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/apa?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/apa?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/apa?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													APA
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/associacao-brasileira-de-normas-tecnicas?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/associacao-brasileira-de-normas-tecnicas?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/associacao-brasileira-de-normas-tecnicas?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													ABNT
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/chicago-author-date?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/chicago-author-date?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/chicago-author-date?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													Chicago
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/harvard-cite-them-right?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/harvard-cite-them-right?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/harvard-cite-them-right?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													Harvard
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/ieee?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/ieee?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/ieee?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													IEEE
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/modern-language-association?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/modern-language-association?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/modern-language-association?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													MLA
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/turabian-fullnote-bibliography?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/turabian-fullnote-bibliography?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/turabian-fullnote-bibliography?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													Turabian
												</a>
											</li>
																					<li>
												<a
													aria-controls="citationOutput"
													href="[https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/vancouver?submissionId=9769&amp;publicationId=9753](https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/vancouver?submissionId=9769&publicationId=9753)"
													data-load-citation
													data-json-href="https://journal.uokufa.edu.iq/index.php/kmj/citationstylelanguage/get/vancouver?submissionId=9769&amp;publicationId=9753&amp;return=json"
												>
													Vancouver
												</a>
											</li>
																			</ul>
																			<div class="label">
											Download Citation
										</div>
										<ul class="citation_formats_styles">`

**Comment by saalam** [comment]
Hi @seboettg 
PKP team were able to solve the problem. @asmecher were able to solve to update the required libraries. Please see  [Permit newer dependencies in citationStyleLanguage plugin to resolve PHP warnings #8657](https://github.com/pkp/pkp-lib/issues/8657)
