### ISSUE TITLE
Error after upgrade to "seboettg/collection": "4.0.0"

### ISSUE THREAD

**Issue by burki** [seboettg/citeproc-php#181]
Attempted to call an undefined method named "hasKey" of class "Seboettg\Collection\ArrayList".
at vendor\seboettg\citeproc-php\src\Locale\LocaleXmlParserTrait.php:132:

   if ($child->getName() !== "name-part" && !$this->terms->hasKey($name)) {

Downgrading seboettg/collection (v4.0.0 => v3.1.0) solves the issue (keeping seboettg/citeproc-php at v2.6.1).

Please let me know if you need a minimal test case to reproduce this issue.

**Comment by seboettg** [comment]
Oh yes, version 4 of `seboettg/collection` has a lot of breaking changes. I'm going to make fix asap by fixating `seboettg/collection` to version `3.*`.

**Comment by seboettg** [comment]
Done. Please check the hotfix release for citeproc-php.

**Comment by burki** [comment]
Solved by 4070bdc3ad1c5fa1cfe3887f2db70f281a50e4a7
