### ISSUE TITLE
Substitution problem

### ISSUE THREAD

**Issue by cenkdominic** [seboettg/citeproc-php#41]
> If cs:substitute contains multiple child elements, the first element to return a non-empty result is used for substitution. Substituted variables are suppressed in the rest of the output to prevent duplication.

I’m running into a problem with substitutions. 
Example: 
In APA style, when the author is missing they are substituted by the Title. But it seems like the Title variable is then not being suppressed, leading to something that looks like this: 

`Title. (Year). Title. Publisher. Retrieved July 27, 2017 from URL`

The second Title variable should not be there. I’ve looked around the code but could not see where to change this. Am I missing something?

**Comment by seboettg** [comment]
Hey Cenk,

thank you for this hint!

I took a quick look at the source code and if i didn't overlook nothing, then I have forget to implement the suppression of variables (that are used elsewhere as substitution) to prevent duplication. It would cause a bigger problem to implement this... The processor runs through styles definitions serially and generates just an output string. It's hard to distinguish elsewhere the origin of different substrings within that string to remove these (if necessary). 

This could mean, that a complete different approach is necessary for the generation of the output. 

Possibly it's a good idea to generate an output tree data structure. Thus one is able to manipulate a tree like that before the output will be rendered. In your case of the APA style the leaf "title" would be removed before the writing of the output starts.

What do you think?

**Comment by cenkdominic** [comment]
Hey Sebastian, 

Thank you for your response! 

Disclaimer: I’m no PHP wizard, so I’m just wildly guessing here. 
Might it be possible to take the string that is generated and search it for duplicate substrings, and then remove the second one? Although this would probably open up a whole lot of other problems … 

Generating it in a tree data structure is probably best. Is there any way I can help without knowing a lot of PHP?

**Comment by seboettg** [comment]
> Is there any way I can help without knowing a lot of PHP?

I guess not... 

I have to spend a bit time to think about possible solutions. Unfortunately, you have to be patient for a solution until I have enough time in order to occupy myself with that.

**Comment by cenkdominic** [comment]
Any new ideas on this? Is there a workaround I can do in the meantime?

**Comment by seboettg** [comment]
I guess I've found a solution that is easily to implement and saves a lot of time. In order to avoid a complete rebuild of the data structure, I'm going to try this way first.

**Comment by seboettg** [comment]
@cenkdominic I guess I have a suitable solution. In order to test it, I need your example metadata which caused the problem. Please post it here. Thx :)

**Comment by seboettg** [comment]
please try out release 2.0.2

**Comment by cenkdominic** [comment]
Here’s a quick example, I will test 2.0.2 today and get back to you. 

`{
	"type": "article-journal",
	"id": "2_243897",
	"title": "Grande Expectations: a Year in the Life of Starbucks Stock",
	"DOI": "10.1108/00251740810865120      ",
	"issued": {
		"date-parts": [
			["2008"]
		]
	}
}`

**Comment by cenkdominic** [comment]
It works perfectly with 2.0.2! Thank you so much 👍🏽
