### ISSUE TITLE
Integrated into OJS 3.1

### ISSUE THREAD

**Issue by NateWr** [seboettg/citeproc-php#43]
Hi @seboettg, I wanted to let you know we've integrated `citeproc-php` into Open Journal Systems v3.1, which we expect to release in the next month or so. Your library allowed us to get rid of thousands of lines of our own code to generate article citations, and will make it easier for users to take advantage of any of the many existing CSL styles. I just wanted to say thanks. Our development issue is https://github.com/pkp/pkp-lib/issues/723

**Comment by seboettg** [comment]
<3 Thank you! I'm very happy to know that my code helps you.
