### ISSUE TITLE
Missing title with chicago-fullnote-bibliography

### ISSUE THREAD

**Issue by lnprieto** [seboettg/citeproc-php#44]
Hi
With chicago-fullnote-bibliographyn the item's title isn't displayed. It is displayed in others formats.
I tried the example given in the README and the same occurs : no title.
The condition <if variable="title" match="none"> is true.
We used to use the old library academicpuma/citeproc-php and with it, titles are displayed. But with it we had other problems that have been solved in this version. 
Is there a way to have the title displayed ?
Thank you in advance

**Comment by seboettg** [comment]
Hi,
Thank you for this comment.
In order to reproduce your issue, I need the input data, with which the error occurred.

**Comment by lnprieto** [comment]
Thank for this quick answer.
I reproduce this with the data given in the README, which is simpler than ours 

[
    {
        "author": [
            {
                "family": "Doe", 
                "given": "James", 
                "suffix": "III"
            }
        ], 
        "id": "item-1", 
        "issued": {
            "date-parts": [
                [
                    "2001"
                ]
            ]
        }, 
        "title": "My Anonymous Heritage", 
        "type": "book"
    },
    {
        "author": [
            {
                "family": "Anderson", 
                "given": "John"
            }, 
            {
                "family": "Brown", 
                "given": "John"
            }
        ], 
        "id": "ITEM-2", 
        "type": "book",
        "title": "Two authors writing a book"
    }
]

**Comment by seboettg** [comment]
Looks like the "none" conditions don't work.

The if condition matches, although title exists. Thus, "else-if" and "else" can't never reached.

    <choose>
        <if variable="title" match="none">  
            .... 
        </if>
        <else-if type="book graphic motion_picture song" match="any">
            ...
        </else-if>
        <else>
            ...
        </else>
    <choose>

I'm working on a solution to the problem.

**Comment by seboettg** [comment]
The bug is solved with release [v2.0.3](https://github.com/seboettg/citeproc-php/releases/tag/v2.0.3).

Thank you for reporting this bug!

**Comment by lnprieto** [comment]
Great ! Thank you very much !
