### ISSUE TITLE
quotes not displayed for title in chicago-fullnote-bibliography

### ISSUE THREAD

**Issue by lnprieto** [seboettg/citeproc-php#45]
Hi
Sorry, we have more issues.
The first one is still with chicago-fullnote-bibliography : no quotes displayed around the title. However the line 287 of chicago-fullnote-bibliography.csl is applied, I checked. And according to this line the quotes should be. 
Quotes are displayed for other formats (apa, mla)
Furthermore, with chicago format, no volume indications or pages are displayed
Data are 
`[{"indexed":{"date-parts":[[2017,5,27]],"date-time":"2017-05-27T11:32:49Z","timestamp":1495884769621},"reference-count":0,"publisher":"PERSEE Program","issue":"529","content-domain":{"domain":[],"crossmark-restriction":false},"short-container-title":["geo"],"published-print":{"date-parts":[[1986]]},"DOI":"10.3406\/geo.1986.20425","type":"journal-article","created":{"date-parts":[[2008,10,16]],"date-time":"2008-10-16T09:12:30Z","timestamp":1224148350000},"page":"341-361","source":"Crossref","is-referenced-by-count":3,"title":"Les premiers cours de g\u00e9ographie de Paul Vidal de la Blache \u00e0 Nancy (1873-1877)","prefix":"10.3406","volume":"95","author":[{"given":"Howard F.","family":"Andrews","affiliation":[]}],"member":"2000","container-title":"Annales de G\u00e9ographie","original-title":[],"deposited":{"date-parts":[[2008,10,16]],"date-time":"2008-10-16T09:07:12Z","timestamp":1224148032000},"score":1.0,"subtitle":[],"short-title":[],"issued":{"date-parts":[[1986]]},"references-count":0,"URL":"http:\/\/dx.doi.org\/10.3406\/geo.1986.20425","relation":{},"ISSN":["0003-4010"],"issn-type":[{"value":"0003-4010","type":"print"}],"subject":["Earth-Surface Processes","Geography, Planning and Development"]}]`

Can you help us...again ?
Thank you in advance for your help

**Comment by seboettg** [comment]
I guess this problems occurs due to erroneous meta data. In your example the type is defined as "journal-article". According to the specifications (have a look [here](https://github.com/citation-style-language/schema/blob/master/csl-data.json#L13)) the type must be "article-journal".

Change the value of the type attribute in your meta data from journal-article to article-journal and everything works as expected.

**Comment by lnprieto** [comment]
Right...thank you for your help !

**Comment by seboettg** [comment]
You're welcome 👍  
If you have further questions, feel free to ask!
