### ISSUE TITLE
initialize not works for cyrillic symbols

### ISSUE THREAD

**Issue by litvinovg** [seboettg/citeproc-php#46]
Looks like citepro-php implementation of CSL used in OJS can’t make initials from cyrillic given. 
For example with Name and middle name in latin characters it works https://pj.iph.ras.ru/index.php/ph_j/article/view/46
And with cyrillic not https://pj.iph.ras.ru/index.php/ph_j/article/view/31
That’s my csl configuration for author:
\<name initialize-with=". " initialize=“true” name-as-sort-order=“first” sort-separator=" ">

**Comment by seboettg** [comment]
Looks like this occurs due to wrong character encoding. citeproc-php expects UTF-8.
Before passing the JSON formatted metadata to the render function, you should convert the string to UTF-8:

    
    $data = mb_convert_encoding($data, "UTF-8");
    $citeProc->render(json_decode($data), "bibliography");

**Comment by litvinovg** [comment]
Thanks! I'll try it out.

**Comment by seboettg** [comment]
Thank you! If it is still not working, I need the metadata of some examples in order to reproduce this problem.

**Comment by litvinovg** [comment]
This is my citationData printed to log in json:
{
   "type":"article-journal",
   "id":"31",
   "title":"Proclus\\u2019 metaphysics: between worldview and language game. Reflections on the book of Radek Chlup",
   "container-title":"Philosophy Journal",
   "container-title-short":"PhJ",
   "volume":"8",
   "issue":"1",
   "section":"ACADEMIC DISCUSSIONS",
   "URL":"https://pj.iph.ras.ru/index.php/ph_j/article/view/31",
   "accessed":{
      "raw":""
   },
   "author":[
      {
         "family":"\\u041c\\u0435\\u0441\\u044f\\u0446",
         "given":"\\u0421\\u0432\\u0435\\u0442\\u043b\\u0430\\u043d\\u0430 \\u0412\\u0438\\u043a\\u0442\\u043e\\u0440\\u043e\\u0432\\u043d\\u0430"
      }
   ],
   "issued":{
      "raw":"2015-03-05 00:00:00"
   },
   "page":"7-22"
}

**Comment by litvinovg** [comment]
It seems that it is already in UTF-8. mb_convert_encoding for each data value didn't help.

**Comment by seboettg** [comment]
Okay, I'm going to test and debug with IEEE. The output should look as follow, right?

> С. В. Месяц, “Proclus’ metaphysics: between worldview and language game. Reflections on the book of Radek Chlup,” <i>Philosophy Journal</i>, vol. 8, no. 1, pp. 7-22, Mar. 2015.

**Comment by litvinovg** [comment]
Yes.

**Comment by seboettg** [comment]
Okay, Problem should be solved.
Try out the following steps.

cd to your software root directory that uses citeproc-php and update citeproc using composer

    $ composer clearcache 
    $ composer require seboettg/citeproc-php:dev-hotfix/citeproc-php-46

**Comment by litvinovg** [comment]
It works well now! Thanks a lot.

**Comment by seboettg** [comment]
Great! I'm going to merge the branch and release v2.0.4 soon.
