### ISSUE TITLE
CSS rendering does not match CSL online configurator rendering

### ISSUE THREAD

**Issue by silence-cube** [seboettg/citeproc-php#57]
### Bug reports:

We have the issue with apa-style, that the rendering differs from the rendering of the CSL Online Configurator. It seems that the `padding-left` + `text-indent` CSS trick is missing for citeproc-php.

# Rendering using citeproc-php:
![image](https://user-images.githubusercontent.com/3079050/45080058-50dd7680-b0f4-11e8-8a8f-f0852704c474.png)
![image](https://user-images.githubusercontent.com/3079050/45080342-fd1f5d00-b0f4-11e8-8e87-66c9b490cbfb.png)

# Rendering of [reference website](http://editor.citationstyles.org/styleInfo/?styleId=http%3A%2F%2Fwww.zotero.org%2Fstyles%2Fapa)
![image](https://user-images.githubusercontent.com/3079050/45080144-7c606100-b0f4-11e8-896c-3c595fb658de.png)
![image](https://user-images.githubusercontent.com/3079050/45080308-e7119c80-b0f4-11e8-800b-048ff097d07f.png)

#### Used CSL stylesheet: ####
apa

**Comment by silence-cube** [comment]
Thanks, yes apa is working now properly!

**Comment by silence-cube** [comment]
Is there an estimation when a new release with this issue will be released? @seboettg

**Comment by seboettg** [comment]
Version 2.1.5 has been released which includes the bugfix. Please close this ticket if everything works as expected.

**Comment by seboettg** [comment]
I assume the error is fixed and close the ticket now.
