### ISSUE TITLE
Undesirable data change after rendering

### ISSUE THREAD

**Issue by artbovboosta** [seboettg/citeproc-php#58]
# Please follow the general troubleshooting steps first:

- [ +] I read the README and followed the instructions.
- [ +] I am sure that the used CSL metadata follows the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).
- [ +] I use a valid CSL stylesheet

### Bug reports:

Object `$data` contains different data before and after `$citeProc->render($data, "bibliography");` operation.

Full code:
```
$data = file_get_contents("metadata_test.json");
$data = json_decode($data);

echo '<pre>'; print_r($data); echo '</pre>';

$style = StyleSheet::loadStyleSheet('apa');
$citeProc = new CiteProc($style);
echo $citeProc->render($data, "bibliography");

echo '<pre>'; print_r($data); echo '</pre>';
```
The result is:
![image](https://user-images.githubusercontent.com/37540289/45750895-270a7080-bc19-11e8-8466-2eb264c76105.png)

In class [Text.php](https://github.com/seboettg/citeproc-php/blob/master/src/Seboettg/CiteProc/Rendering/Text.php#L106), on line 106, there is "unset" operation which removes `title` field.

As objects are passed by references by default, I suggest to clone those objects before processing.

P.S. I noticed that this issue occurs only when `"type": "webpage"` and there is no authors.

#### Used CSL stylesheet: ####

apa

#### Used CSL metadata ####

[
  {
    "URL": "www.starwars.com/",
    "accessed": {
      "date-parts": [
        [
          "2018",
          "09",
          "19"
        ]
      ]
    },
    "id": "item-1",
    "title": "StarWars.com | The Official Star Wars Website",
    "type": "webpage"
  }
]

**Comment by seboettg** [comment]
Thank you for this bug report. Version 2.1.5 has been released which should solve this bug. Please close this issue if everything works properly.

**Comment by artbovboosta** [comment]
Everything works fine.
Thanks a lot!
