### ISSUE TITLE
No verification for existing of "author" property in Util/NameHelper.php on line 29

### ISSUE THREAD

**Issue by artbovboosta** [seboettg/citeproc-php#59]
# Please follow the general troubleshooting steps first:

- [+] I read the README and followed the instructions.
- [+] I am sure that the used CSL metadata follows the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).
- [+] I use a valid CSL stylesheet

### Bug reports:
Using specified below CSL stylesheet and CSL metadata I got following error notices:
![image](https://user-images.githubusercontent.com/37540289/46020306-bcf53e00-c0e6-11e8-817c-a35212aa7381.png)

There are no verification for existing of "author" property.
Can you fix this, please?

#### Used CSL stylesheet: ####

modern-language-association

#### Used CSL metadata ####

Please replace these lines with your used metadata, for instance:

[
  {
    "type": "book",
    "accessed": {
      "date-parts": [
        [
          "2016",
          "01",
          "01"
        ]
      ]
    },
    "publisher": "lol2",
    "title": "lol"
  },
  {
    "type": "book",
    "author": [
      {
        "given": "Daniel",
        "suffix": "H.",
        "family": "Nexon"
      },
      {
        "given": "Iver",
        "suffix": "B.",
        "family": "Neumann"
      }
    ],
    "accessed": {
      "date-parts": [
        [
          "2006",
          "01",
          "01"
        ]
      ]
    },
    "publisher": "Rowman & Littlefield",
    "title": "Harry Potter and International Relations"
  }
]

**Comment by seboettg** [comment]
Thank you for this report! In release [2.1.6](https://github.com/seboettg/citeproc-php/releases/tag/v2.1.6) this issue should be solved.

**Comment by seboettg** [comment]
please reopen this issue, if the issue reappears.
