### ISSUE TITLE
line-height differerent from editor.citationstyles.org

### ISSUE THREAD

**Issue by wapp-its** [seboettg/citeproc-php#61]
Stylesheet: apa.csl

The line-height is different between citeproc-php and editor.citationstyles.org. Problem is that the line height within one entry is the same as between multiple entries.

**This is how it should look** (margin between two entries and small line height within one entry):
![2018-10-22 09_54_46-style info](https://user-images.githubusercontent.com/26138299/47282900-3185a480-d5e1-11e8-9819-a06cb42705cf.png)

**This is how it looks with citeproc-php:**
![2018-10-22 10_01_40-publikationen _ fakultat fur psychologie](https://user-images.githubusercontent.com/26138299/47283012-b4a6fa80-d5e1-11e8-8ef8-e94f56aeb6aa.png)

Because of the inline css:
![2018-10-22 09_55_23-publikationen _ fakultat fur psychologie](https://user-images.githubusercontent.com/26138299/47283022-bd97cc00-d5e1-11e8-805d-affd4d0514f9.png)

We could override it with our css style-sheets, but in case this is not intended we will wait for a fix of citeproc-php. Eventually it's enough to simply remove the line-height ?

**Comment by wapp-its** [comment]
@seboettg happy new year! 

Can you confirm this issue?

**Comment by seboettg** [comment]
I wouldn't define it as a bug, rather than as an improvement. If you interested in a quick solution, I would suggest you to make a PR. Afterwards, I might release a new version.

**Comment by seboettg** [comment]
Hi @wapp-its! 
I took a closer look to this issue. According to [specification](http://docs.citationstyles.org/en/stable/specification.html#whitespace) line-spacing specifies the vertical line distance and entry-spacing the vertical distance between entries. APA style for bibliographes provides line-spacing of 2: `<bibliography hanging-indent="true" et-al-min="8" et-al-use-first="6" et-al-use-last="true" entry-spacing="0" line-spacing="2">`. Accordingly, citeproc-php behaves as expected. Or do you have another opinion?

**Comment by seboettg** [comment]
@wapp-its can you give me an answer? otherwise I'd close this ticket.

**Comment by seboettg** [comment]
I'm going to close this ticket for now. If there is still a need for action, please reopen the ticket.

**Comment by wapp-its** [comment]
Thanks for your investigation. You are right, this seems to be a correct behavior! In this case the CSL online editor has a bug.
