### ISSUE TITLE
Layout.php line formatting is brought into the rendered page as returns

### ISSUE THREAD

**Issue by nchiasson-dgi** [seboettg/citeproc-php#67]
https://github.com/seboettg/citeproc-php/blob/master/src/Rendering/Layout.php#L100
https://github.com/seboettg/citeproc-php/blob/master/src/Rendering/Layout.php#L175

The formatting added with the "\n" and the double spaces in line 175, and the "\n" in line 100 cause returns to be added to the text output.

Not the end of the world, but it'll otherwise need to be handled by the user.

**Comment by seboettg** [comment]
Hi @nchiasson-dgi!
Thank for reporting this issue. Unfortunately, I do not understand what you would like to have changed... Would you like to have the "newline" removed?

**Comment by seboettg** [comment]
Since I have received no response to my question, I am going to close this ticket now.

**Comment by nchiasson-dgi** [comment]
I'm sorry! I missed this question. Maybe it's too little too late, though I believe the intention was to have the new-line characters removed, as I noticed that they got included in the citation message output.
