### ISSUE TITLE
Match "any" not working in Variable

### ISSUE THREAD

**Issue by tiago-sb** [seboettg/citeproc-php#69]
### Bug reports:

Unlike, for example, the constraint Type(.php), which supports something like

`<else-if type="bill book graphic legislation motion_picture report song" match="any">`

the constraint Variable(.php) does not support something like

`<else-if variable="publisher-place publisher" match="any">`

... and from what I understand in http://docs.citationstyles.org/en/stable/specification.html#choose (near the end of this section) it should ->
> With the exception of disambiguate, all conditions allow for multiple test values (separated with spaces, e.g. “book thesis”).

#### Used CSL stylesheet: ####

modern-humanities-research-association.csl

#### Used CSL metadata ####

```
[{
   "id":"7021352\/UTSP92QZ",
   "type":"book",
   "title":"Early Sixteenth-Century Sacred Music from the Papal Chapel",
   "collection-title":"Corpus Mensurabilis Musicae",
   "collection-number":"95-2",
   "publisher":"American Institute of Musicology, Ha\u0308nssler-Verlag",
   "publisher-place":"Neuhausen-Stuttgart",
   "volume":"II",
   "event-place":"Neuhausen-Stuttgart",
   "language":"en",
   "editor":[
      {
         "family":"Josephson",
         "given":"Nors S."
      }
   ],
   "issued":{
      "date-parts":[
         [
            1982
         ]
      ]
   }
}]

```

**Comment by seboettg** [comment]
Hi @tiago-sb 
Nice catch... Thank you for finding this and yes, you're absolutely right with this issue. I'm wondering a bit why nobody noticed this before. Anyhow, I'm going to fix it soon.

**Comment by seboettg** [comment]
Hi @tiago-sb,
I fixed this issue and also #70 and #71. I will prepare a new release soon. If you are curious, you are welcome to checkout the master branch for some tests.

**Comment by tiago-sb** [comment]
Hi Sebastian,

That is great news, thanks!
I’ll test the master branch later today or tomorrow and will let you know how it goes. 

Thanks again for this great tool and for the quick response.

Tiago

**Comment by tiago-sb** [comment]
Hi @seboettg,

tested with master branch and this fix is working as expected, at least for the scenario of this issue :)

Thanks
