### ISSUE TITLE
Closing parenthesis missing in BibTeX exports

### ISSUE THREAD

**Issue by hllizi** [seboettg/citeproc-php#72]
I'd briefly like to point out the two issues resolved in a perhaps rather brutish fashion [here](https://github.com/hllizi/citeproc-php/issues?q=is%3Aissue+is%3Aclosed).

At two different places in the code it is ascertained that, when exporting to BibTeX, the last curly parenthesis will be missing in the resulting record if it should end with two parentheses, which is quite common, e.g.:  

`> @book{ ..., year={1978}}`

Both issues were resolved by simply removing the application of the code that would prevent the doubling of parentheses, without any regard for the intended effects it might have in other places. Testing was not possible, unfortunately, since running the tests for both the original repository and my modifications resulted in a segmentation fault on my debian stretch machine.

At the moment, unfortunately, I do not have the resources to dig any deeper and must leave it at that.

**Comment by seboettg** [comment]
Hi David!
I would suggest you send your changes as a pull request. I have integrated Scrutinizer CI for this repo. All tests should be executed automatically. Thus, we can see if your changes cause any side effects. It's also easier for me to work on your changes if necessary.

**Comment by seboettg** [comment]
Further discussions in [PR73](https://github.com/seboettg/citeproc-php/pull/73).
