### ISSUE TITLE
PHP RFC: Deprecate curly brace syntax for accessing array elements and string offsets

### ISSUE THREAD

**Issue by westcomputerconsultancy** [seboettg/citeproc-php#78]
Afternoon,

There are a number of places where curly braces have been used as an array index. These are deprecated in php7.4. I've modified the files, rescanned in PHPCS and all seems to pass now.

Thanks,

Stephen

[src.zip](https://github.com/seboettg/citeproc-php/files/4334325/src.zip)

**Comment by westcomputerconsultancy** [comment]
Pull request submitted.

**Comment by seboettg** [comment]
Hi @westcomputerconsultancy 
thanks for reporting this issue. Unfortunately, I had no time to take care of cireproc-php in the last few weeks. I'm going to solve this issues in the next days and make citeproc-php fit up to php 7.4.

**Comment by westcomputerconsultancy** [comment]
Thanks very much. It will help much.

**Comment by seboettg** [comment]
Hi @westcomputerconsultancy!
I merged your pull request.
Please also check if your issues are solved with the latest commit https://github.com/seboettg/citeproc-php/commit/6258cd9c49264a5bc1b357211a5c670b7da9d937
Thank you in advance!

**Comment by westcomputerconsultancy** [comment]
That's great. Many thanks. All seems to be working fine now with PHP7.4.

**Comment by seboettg** [comment]
Version 2.2.0 has been released. I think the issue should be solved. If not, feel free to reopen this ticket.
