### ISSUE TITLE
Strangely result on php7.3

### ISSUE THREAD

**Issue by navotera** [seboettg/citeproc-php#80]
Hi, I am OJS user and based on the OJS developer they used this library for their citation plugin. Unfortunately there is weird result when I using php7.2 vs php7.3. 

With same codebase (just change the PHP version) the output resulted with different citation result : 
PHP 7.2 
AuthorLastName, AuthorLastNameFirstNameCapitalized .....
Example : 
Price, M., & Wayne, B. (2019)

PHP 7.3 : 
AuthorLastNameAuthorLastNameFirstNameCapitalized
Example : 
PriceM., & WayneB. (2019)

Others user also reported same issue : 
https://forum.pkp.sfu.ca/t/ojs-3-1-0-1-plugin-citation-style-language-prints-how-cite-info-without-comma-and-space/50106/5

Can you give some clue how this can be happen and how to solve this on php7.3.  ? 

Thank you

**Comment by hcoussy** [comment]
Hello,
At the University of Bordeaux we host several journals in OJS 3.1.2-4 and we have noticed the same issue when we upgraded to PHP 7.3.
We would be also interested to know if the problem have been identified and that if it can be solved ?
Thanks in advance for your answer.
Best regards.
Helene

**Comment by seboettg** [comment]
Hi @navotera and @hcoussy,

thank for reporting this issue. Unfortunately, I had no time to take care of cireproc-php in the last few weeks. I'm going to solve this issues in the next days and make citeproc-php fit up to php 7.4.

**Comment by navotera** [comment]
Thank for your reply @seboettg

**Comment by seboettg** [comment]
Hi @navotera and @hcoussy!
please check if this issue is solved with the latest commit https://github.com/seboettg/citeproc-php/commit/6258cd9c49264a5bc1b357211a5c670b7da9d937
Thank you in advance!

**Comment by navotera** [comment]
Dear @seboettg 

Thank for updating this. I find hard to test it on OJS system since this library integrated with OJS system. I try to copy paste this code and resulted with error 500. 

I let the OJS team to notify about this update. 
Thank you.

**Comment by NateWr** [comment]
HI @seboettg, thanks for the update. I work on OJS so I can test the update. Is there a release package that I should test or is the `master` branch sufficient?

**Comment by seboettg** [comment]
Hi @NateWr!
Thank you for your help! Just checkout the `master` branch in order to perform these tests. If the tests were successful, I will prepare a release soon.

**Comment by NateWr** [comment]
Fix confirmed! Thanks as always for your excellent stewardship of this library. :+1:

**Comment by seboettg** [comment]
Hi @NateWr, @navotera, @hcoussy 
Version 2.2.0 has been released. Please update citeproc-php and check again if the issues are solved. If yes, please close this ticket.

**Comment by navotera** [comment]
Let's wait for @NateWr  to confirm that the version will result the fix on their OJS system. 
Thank you @seboettg

**Comment by NateWr** [comment]
Fix confirmed! @navotera and @hcoussy please follow https://github.com/pkp/pkp-lib/issues/5629 for updates related to OJS.
