### ISSUE TITLE
Rendered html is invalid

### ISSUE THREAD

**Issue by RazielleS** [seboettg/citeproc-php#89]
I have set up an example for you here: https://github.com/RazielleS/citeproc-bug-demo

In the second entry of the demo.json, we use a `<` in the title.
This character is not replaced by its html equivalent (`&lt;`), so we get invalid XML out of this.

I do not think it should be necessary to encode the html entities in the Json directly, as I encountered other issues this way.

**Comment by seboettg** [comment]
Hi @RazielleS!
Thank you for this bug report. My last commit should solve the issue. Please checkout the master branch, run `composer update` and test again. I'm going to prepare a new release, as soon as you confirm the fix.

**Comment by seboettg** [comment]
Hallo @RazielleS?
Please check if the issue is solved.

**Comment by RazielleS** [comment]
Sorry, I was absent for a while.

I just tested with the master branch: This issue is solved.
Thank you very much

**Comment by seboettg** [comment]
Solved with [v2.2.1](https://github.com/seboettg/citeproc-php/releases/tag/v2.2.1).
