### ISSUE TITLE
Dot is rendered below item if DOI is not set

### ISSUE THREAD

**Issue by RazielleS** [seboettg/citeproc-php#92]
# Please follow the general troubleshooting steps first:

- [x] I read the README and followed the instructions.
- [x] I am sure that the used CSL metadata follows the [CSL schema](https://github.com/citation-style-language/schema/blob/master/csl-data.json).
- [x] I use a valid CSL stylesheet

### Bug reports:
![image](https://user-images.githubusercontent.com/8451816/93903955-92e8ad80-fcf9-11ea-96a3-c1f595e4ea5f.png)

When there is no DOI set, one `.` is rendered below the item.
This does not happen when testing on https://editor.citationstyles.org/visualEditor/. Although I need to change the DOI from `null` to an empty string there, otherwise it does not work at all.
This does not work here. When changing to an empty string, an empty DOI is rendered instead:
![image](https://user-images.githubusercontent.com/8451816/93904142-cfb4a480-fcf9-11ea-817a-cc45adbc87e4.png)

#### Used CSL stylesheet: ####
acm-sig-proceedings-long-author-list

#### Used CSL metadata ####

```json
[
  {
    "type": "article-journal",
    "title": "[Book Review on] Margit V. Wunsch Gaarmann: The War in Our Backyard: The Bosnia and Kosovo Wars through the Lens of the German Print Media. Berlin 2015",
    "collection-title": null,
    "collection-number": null,
    "container-title": "Laboratorium 2015",
    "abstract": "The wars in Bosnia (1992–1995) and Kosovo (1998–1999) caused Germany to seriously consider military intervention abroad for the first time since the Second World War. The political stance taken by the then-recently reunited Germany towards the so-called Balkan wars was largely negotiated by the national public press. In The War in Our Backyard Margit V. Wunsch Gaarmann analyses how these two wars—and the political debates they triggered—were portrayed by the German press. Her study can be seen as a part of a larger field of research dealing with the connection between media and war. In her book Gaarmann presents a differentiated image of the German media, demonstrating that reports were far more controversial than suggested by the academic literature to date.",
    "page": "206-209",
    "number-of-pages": null,
    "event-place": null,
    "event-date": null,
    "ISSN": "2076-8214",
    "ISBN": null,
    "language": null,
    "genre": null,
    "country": null,
    "volume": 7,
    "issue": 2,
    "publisher": "CNSI",
    "publisher-place": null,
    "keyword": null,
    "DOI": null,
    "PMID": null,
    "note": "Publication type according to Uni Basel Research Database: Journal article",
    "URL": null,
    "author": [
      {
        "family": "Freiermuth Samardzic",
        "given": "Nadine"
      }
    ],
    "editor": [],
    "issued": {
      "date-parts": [
        [
          "2015"
        ]
      ]
    }
  }
]
```

**Comment by seboettg** [comment]
Hi @RazielleS!
Thank you for this report! I fixed the bug. But it doesn't matter whether the DOI is set or not. 
citeproc-php as well as citeproc-js can not always handle CSL input data that contains null values/empty values. So it would be better to cleanup the data before try to render it.

For a test case I removed all empty values (empty strings, empty arrays, null values) and everything works fine with both, citeproc-php and citeproc-js

```json
[
    {
        "ISSN": "2076-8214", 
        "abstract": "The wars in Bosnia (1992–1995) and Kosovo (1998–1999) caused Germany to seriously consider military intervention abroad for the first time since the Second World War. The political stance taken by the then-recently reunited Germany towards the so-called Balkan wars was largely negotiated by the national public press. In The War in Our Backyard Margit V. Wunsch Gaarmann analyses how these two wars—and the political debates they triggered—were portrayed by the German press. Her study can be seen as a part of a larger field of research dealing with the connection between media and war. In her book Gaarmann presents a differentiated image of the German media, demonstrating that reports were far more controversial than suggested by the academic literature to date.", 
        "author": [
            {
                "family": "Freiermuth Samardzic", 
                "given": "Nadine"
            }
        ], 
        "container-title": "Laboratorium 2015", 
        "issue": 2, 
        "issued": {
            "date-parts": [
                [
                    "2015"
                ]
            ]
        }, 
        "note": "Publication type according to Uni Basel Research Database: Journal article", 
        "page": "206-209", 
        "publisher": "CNSI", 
        "title": "[Book Review on] Margit V. Wunsch Gaarmann: The War in Our Backyard: The Bosnia and Kosovo Wars through the Lens of the German Print Media. Berlin 2015", 
        "type": "article-journal", 
        "volume": 7
    }
]
```

**Comment by seboettg** [comment]
@RazielleS One more thing: Please checkout branch `issue-92`, test the fix and confirm it when everything works as expected. Thank you!

**Comment by RazielleS** [comment]
@seboettg Thank you, the bugfix is working.

I'll have a look if we can remove the null values somehow. Thanks for the suggestion.

**Comment by seboettg** [comment]
I'm glad to hear that. I'm going to make a hotfix release soon.

**Comment by seboettg** [comment]
Hi @RazielleS!
Version [2.2.2](https://packagist.org/packages/seboettg/citeproc-php#v2.2.2) has been released and contains this fix. I will close this bug report now. If you have some trouble with the described bug, feel free to reopen this ticket.
