### ISSUE TITLE
Ellipsis is removed in journal article title that contain an ellipsis

### ISSUE THREAD

**Issue by westcomputerconsultancy** [seboettg/citeproc-php#98]
In journal article titles that contain an ellipsis then the ellipsis is removed (by the ConsecutivePunctuationCharacterTrait trait). E.g.

Sabatos, Charles. “Czechs, Sex, Spies and Torture: Slovak Identity As Translation in Vilikovsky’s ‘Ever Green is.’.” Comparative Literature Studies 40.2 (2003): 173–192. Print.

instead of 

Sabatos, Charles. “Czechs, Sex, Spies and Torture: Slovak Identity As Translation in Vilikovsky’s ‘Ever Green is...’.” Comparative Literature Studies 40.2 (2003): 173–192. Print. 

I would offer a fix but I am not sure how you would want to handle the change. If I can help please let me know.

#### Used CSL stylesheet: ####

modern-language-association-7th-edition.csl

#### Used CSL metadata ####
[
  {
    "type": "article-journal",
    "title": "Czechs, Sex, Spies and Torture: Slovak Identity as Translation in Vilikovsky's \"Ever Green is...\"",
    "id": "article-7699",
    "container-title": "Comparative Literature Studies",
    "issue": 2,
    "volume": 40,
    "issued": {
      "date-parts": [
        [
          2003
        ]
      ]
    },
    "page": "173-192",
    "author": [
      {
        "given": "Charles",
        "family": "Sabatos"
      }
    ]
  }
]

**Comment by westcomputerconsultancy** [comment]
I'll close this for now. The recommendation for citations is to use . . . i.e. a space after each full stop which would stop this removal from happening.

**Comment by seboettg** [comment]
Hi @westcomputerconsultancy,
I guess this issue is exactly the same topic as [this one](https://github.com/seboettg/citeproc-php/issues/90).

**Comment by westcomputerconsultancy** [comment]
Thank you. I didn't see that. I also closed the ticket because MLA suggests
an ellipsis should be spaced i.e. . . . which solves the problem for them.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
